<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;
use Carbon\Carbon;

class DevicePairingToken extends Model
{
    protected $table = 'device_pairing_tokens';

    public $timestamps = false; // Only created_at, no updated_at

    protected $fillable = [
        'pairing_token',
        'vendor_id',
        'store_id',
        'generated_by',
        'expires_at',
        'used_at',
        'device_id',
    ];

    protected $casts = [
        'expires_at' => 'datetime',
        'used_at' => 'datetime',
        'created_at' => 'datetime',
    ];

    /**
     * Generate a unique pairing token
     *
     * @return string
     */
    public static function generateToken(): string
    {
        return 'PT-' . strtoupper(Str::random(20));
    }

    /**
     * Check if token is valid (not expired and not used)
     *
     * @return bool
     */
    public function isValid(): bool
    {
        return !$this->isExpired() && !$this->isUsed();
    }

    /**
     * Check if token is expired
     *
     * @return bool
     */
    public function isExpired(): bool
    {
        return $this->expires_at->isPast();
    }

    /**
     * Check if token is already used
     *
     * @return bool
     */
    public function isUsed(): bool
    {
        return $this->used_at !== null;
    }

    /**
     * Mark token as used
     *
     * @param string $deviceId
     * @return bool
     */
    public function markAsUsed(string $deviceId): bool
    {
        return $this->update([
            'used_at' => now(),
            'device_id' => $deviceId,
        ]);
    }

    /**
     * Get QR code data string
     *
     * @return string
     */
    public function getQrData(): string
    {
        $apiUrl = config('app.url');
        return "SNOCART:PAIR:{$this->pairing_token}:{$apiUrl}";
    }

    /**
     * Get time until expiration in seconds
     *
     * @return int
     */
    public function getExpiresInSeconds(): int
    {
        return max(0, now()->diffInSeconds($this->expires_at, false));
    }

    /**
     * Relationship: Vendor
     */
    public function vendor(): BelongsTo
    {
        return $this->belongsTo(Vendor::class, 'vendor_id');
    }

    /**
     * Relationship: Store
     */
    public function store(): BelongsTo
    {
        return $this->belongsTo(Store::class, 'store_id');
    }

    /**
     * Relationship: Generated By Employee
     */
    public function generatedBy(): BelongsTo
    {
        return $this->belongsTo(VendorEmployee::class, 'generated_by');
    }

    /**
     * Scope: Valid tokens only (not expired, not used)
     */
    public function scopeValid($query)
    {
        return $query->whereNull('used_at')
            ->where('expires_at', '>', now());
    }

    /**
     * Scope: Expired tokens
     */
    public function scopeExpired($query)
    {
        return $query->where('expires_at', '<=', now());
    }

    /**
     * Accessor: Is valid
     */
    public function getIsValidAttribute(): bool
    {
        return $this->isValid();
    }

    /**
     * Accessor: Expires in seconds
     */
    public function getExpiresInAttribute(): int
    {
        return $this->getExpiresInSeconds();
    }
}
